apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: {{.Release.Namespace}}
spec:
  ports:
    - name: smtp
      port: {{.Values.mailpit.service.smtp.port}}
      targetPort: {{.Values.mailpit.service.smtp.port}}
    - name: http
      port: {{.Values.mailpit.service.http.port}}
      targetPort: {{.Values.mailpit.service.http.port}}
  selector:
    app: mailpit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: {{.Release.Namespace}}
spec:
  replicas: {{.Values.mailpit.replicaCount}}
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: ghcr.io/axllent/mailpit:latest
          ports:
            - name: smtp
              containerPort: {{.Values.mailpit.service.smtp.port}}
            - name: http
              containerPort: {{.Values.mailpit.service.http.port}}
