version: "3.8"

services:
  erised:
    build:
      context: ./erised
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./erised:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
