apiVersion: v1
kind: Secret
metadata:
  name: vetchi-secrets
  namespace: vetchidev
type: Opaque
stringData:
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "pass"
  POSTGRES_DB: "vdb"
  POSTGRES_PORT: "5432"
  SMTP_PASSWORD: "password"
