apiVersion: v1
kind: Secret
metadata:
  name: vetchi-secrets
  namespace: vetchidev
type: Opaque
data:
  POSTGRES_USER: "dXNlcg=="
  POSTGRES_PASSWORD: "cGFzcw=="
  POSTGRES_DB: "dmRi"
  POSTGRES_PORT: "NTQzMg=="
