apiVersion: v1
kind: Secret
metadata:
  name: vetchi-secrets
  namespace: vetchidev
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: dnV0Y2hpZA==
  POSTGRES_HOST: cG9zdGdyZXM=
