openapi: 3.0.0
info:
  title: Vetchi API
  version: 0.0.1
  description: Vetchi APIs that work across multiple clients

paths:
  /employer/get-onboard-status:
    post:
      tags:
        - Employer
      summary: Get Onboarded Status for a Client
      description: Get Onboarded Status for a Client
      operationId: employer-get-onboard-status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployerGetOnboardStatusRequest"
      responses:
        "200":
          description: OK
        
  /employer/signin:
    post:
      tags:
        - Employer
      summary: SignIn
      description: SignIn to the system
      operationId: employer-signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployerSignInRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmployerSignInResponse"
        "401":
          description: Unauthorized
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ValidationErrors"

components:
  schemas:
    ClientId:
      type: string
      description: The client ID, usually a website domain
      minLength: 3
      maxLength: 255
      example: "example.com"
    EmailAddress:
      type: string
      format: email
      description: An email address
      minLength: 3
      maxLength: 255
      pattern: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
      example: "test@example.com"
    Password:
      type: string
      format: password
      description: A password
      minLength: 8
      maxLength: 255
      example: "Password123$"
      pattern: "^(?:.*[a-z])(?:.*[A-Z])(?:.*\\d)(?:.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$"
    EmployerGetOnboardStatusRequest:
      type: object
      properties:
        client_id:
          $ref: "#/components/schemas/ClientId"
          description: The client ID
    EmployerSignInRequest:
      type: object
      properties:
        client_id:
          $ref: "#/components/schemas/ClientId"
          description: The client ID
        email:
          $ref: "#/components/schemas/EmailAddress"
          description: The email
        password:
          $ref: "#/components/schemas/Password"
          description: The password
    EmployerSignInResponse:
      type: object
      properties:
        token:
          type: string
          description: The authentication token
        expiresAt:
          type: string
          format: date-time
    ValidationErrors:
      type: array
      description: A list of field names for which the validations failed
      items:
        type: string
