apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
  namespace: vetchidevtest
spec:
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
        version: ${GIT_SHA}
    spec:
      containers:
        - name: harrypotter
          image: psankar/vetchi-harrypotter:${GIT_SHA}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_ENDPOINT
              value: "http://hermione:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
  namespace: vetchidevtest
spec:
  type: LoadBalancer
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
