apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
spec:
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
        version: ${GIT_SHA}
    spec:
      containers:
        - name: harrypotter
          image: vetchium/harrypotter:${GIT_SHA}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
spec:
  type: LoadBalancer
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
