apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: vetchidevtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:latest
        ports:
        - containerPort: 1025  # SMTP server
        - containerPort: 8025  # Web UI
        args: ["--listen", "0.0.0.0:8025", "--smtp", "0.0.0.0:1025"]
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: vetchidevtest
spec:
  selector:
    app: mailpit
  ports:
    - protocol: TCP
      port: 1025
      targetPort: 1025
      name: smtp
    - protocol: TCP
      port: 8025
      targetPort: 8025
      name: http
