apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  namespace: vetchidevtest
spec:
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
    spec:
      containers:
        - name: ronweasly
          image: vetchi/ronweasly:${GIT_SHA}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
  namespace: vetchidevtest
spec:
  selector:
    app: ronweasly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
