apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  namespace: vetchidevtest
spec:
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
        version: ${GIT_SHA}
    spec:
      containers:
        - name: ronweasly
          image: psankar/vetchi-ronweasly:${GIT_SHA}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: API_ENDPOINT
              value: "http://granger:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
  namespace: vetchidevtest
spec:
  type: LoadBalancer
  selector:
    app: ronweasly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
