apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
spec:
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
        version: ${GIT_SHA}
    spec:
      containers:
        - name: ronweasly
          image: psankar/vetchi-ronweasly:${GIT_SHA}
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
spec:
  selector:
    app: ronweasly
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
