apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
  namespace: vetchistaging
spec:
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      generateName: harrypotter-${GIT_SHA}-
      labels:
        app: harrypotter
    spec:
      containers:
        - name: harrypotter
          image: psankar/vetchi-harrypotter:${GIT_SHA}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
  namespace: vetchistaging
spec:
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
