apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
  namespace: vetchidev
spec:
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
    spec:
      containers:
        - name: harrypotter
          image: psankar/vetchi-harrypotter
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
  namespace: vetchidev
spec:
  type: LoadBalancer
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
