apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  namespace: vetchidev
spec:
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
    spec:
      containers:
        - name: ronweasly
          image: psankar/vetchi-ronweasly
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
  namespace: vetchidev
spec:
  selector:
    app: ronweasly
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
