apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: vetchium-dev
type: Opaque
stringData:
  host: "mailpit"
  port: "1025"
  user: "user"
  password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: vetchium-dev
type: Opaque
stringData:
  access_key: "minioadmin"
  bucket: "vetchi-tilt-storage"
  endpoint: "http://minio:9000"
  region: "us-east-1"
  secret_key: minioadmin
