apiVersion: v1
kind: ConfigMap
metadata:
  name: sortinghat-config
  namespace: vetchidev
data:
  config.json: |
    {
      "port": "8080"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sortinghat
  namespace: vetchidev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sortinghat
  template:
    metadata:
      labels:
        app: sortinghat
    spec:
      serviceAccountName: sortinghat-sa
      containers:
        - name: sortinghat
          image: psankar/vetchi-sortinghat
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "3"
          env:
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret_key
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: region
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: bucket
          volumeMounts:
            - name: config-volume
              mountPath: /etc/sortinghat-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: sortinghat-config
---
apiVersion: v1
kind: Service
metadata:
  name: sortinghat
  namespace: vetchidev
spec:
  selector:
    app: sortinghat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sortinghat-sa
  namespace: vetchidev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sortinghat-full-access-binding-devtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: sortinghat-sa
    namespace: vetchidev
