apiVersion: v1
kind: Secret
metadata:
  name: smtp-credentials
  namespace: vetchidev
type: Opaque
stringData:
  SMTP_PASSWORD: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: vetchidev
type: Opaque
stringData:
  access_key: "minioadmin"
  bucket: "resumes"
  endpoint: "http://minio:9000"
  region: "us-east-1"
  secret_key: minioadmin
