apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {{ .Values.granger.config | toJson }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.granger.replicas }}
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
    spec:
      containers:
        - name: granger
          image: {{ .Values.granger.image.repository }}:{{ .Values.granger.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: SMTP_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /etc/granger-config
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 