apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
  namespace: {{ .Release.Namespace }}
  labels:
    app: harrypotter
    component: frontend
spec:
  replicas: {{ .Values.harrypotter.replicas }}
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
        component: frontend
    spec:
      containers:
        - name: harrypotter
          image: {{ .Values.harrypotter.image.repository }}:{{ .Values.harrypotter.image.tag }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.harrypotter.config.nextPublic.apiUrl }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
  namespace: {{ .Release.Namespace }}
  labels:
    app: harrypotter
    component: frontend
spec:
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http 