apiVersion: v1
kind: ConfigMap
metadata:
  name: hermione-config
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {{ .Values.hermione.config | toJson }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermione
  namespace: {{ .Release.Namespace }}
  labels:
    app: hermione
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.hermione.replicas }}
  selector:
    matchLabels:
      app: hermione
  template:
    metadata:
      labels:
        app: hermione
    spec:
      initContainers:
      - name: wait-for-migrations
        image: bitnami/kubectl:latest
        command: ['sh', '-c', 'until kubectl get job sqitch-migrations -n {{ .Release.Namespace }} -o jsonpath="{.status.succeeded}" | grep 1; do echo "waiting for sqitch migrations to complete"; sleep 5; done']
      serviceAccountName: hermione-sa
      containers:
        - name: hermione
          image: {{ .Values.hermione.image.repository }}:{{ .Values.hermione.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret_key
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hermione-config
      volumes:
        - name: config-volume
          configMap:
            name: hermione-config
---
apiVersion: v1
kind: Service
metadata:
  name: hermione
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hermione
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hermione-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hermione-full-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: hermione-sa
    namespace: {{ .Release.Namespace }} 