---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app: cnpg-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnpg-controller
  template:
    metadata:
      labels:
        app: cnpg-controller
    spec:
      serviceAccountName: cnpg-controller
      containers:
        - name: manager
          image: ghcr.io/cloudnative-pg/cloudnative-pg:1.22.0
          args:
            - manager
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnpg-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg-controller
rules:
  - apiGroups: ["postgresql.cnpg.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims", "events"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cnpg-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnpg-controller
subjects:
  - kind: ServiceAccount
    name: cnpg-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgresCluster.instances }}
  storage:
    size: {{ .Values.postgresCluster.storage.size }}
  monitoring:
    enablePodMonitor: {{ .Values.postgresCluster.monitoring.enablePodMonitor }}
  bootstrap:
    initdb:
      database: vetchi
      owner: postgres
      secret:
        name: postgres-app
  superuserSecret:
    name: postgres-app
  primaryUpdateStrategy: unsupervised
  inheritedMetadata:
    labels:
      {{- with .Values.postgresCluster.inheritedMetadata.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
