apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.postgresql.cnpg.io
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  group: postgresql.cnpg.io
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instances:
                  type: integer
                storage:
                  type: object
                  properties:
                    size:
                      type: string
                monitoring:
                  type: object
                  properties:
                    enablePodMonitor:
                      type: boolean
                inheritedMetadata:
                  type: object
                  properties:
                    labels:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true 