apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  namespace: {{ .Release.Namespace }}
  labels:
    app: ronweasly
    component: frontend
spec:
  replicas: {{ .Values.ronweasly.replicas }}
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
        component: frontend
    spec:
      containers:
        - name: ronweasly
          image: {{ .Values.ronweasly.image.repository }}:{{ .Values.ronweasly.image.tag }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.ronweasly.config.nextPublic.apiUrl }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
  namespace: {{ .Release.Namespace }}
  labels:
    app: ronweasly
    component: frontend
spec:
  selector:
    app: ronweasly
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http 