apiVersion: v1
kind: Secret
metadata:
  name: vetchi-secrets
  namespace: { { .Release.Namespace } }
type: Opaque
stringData:
  SMTP_PASSWORD: { { .Values.secrets.smtp.password } }
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: { { .Release.Namespace } }
type: Opaque
stringData:
  secret_key: { { .Values.secrets.s3.secretKey } }
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app
  namespace: { { .Release.Namespace } }
type: Opaque
stringData:
  uri: { { .Values.secrets.postgres.uri } }
