apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vetchi-pgdata-pvc
  namespace: vetchidev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vetchidev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: vdb
          volumeMounts:
            - name: pgdata-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata-volume
          persistentVolumeClaim:
            claimName: vetchi-pgdata-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: vetchidev
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
