apiVersion: batch/v1
kind: Job
metadata:
  name: sqitch
  namespace: vetchidev
spec:
  template:
    spec:
      backoffLimit: 5
      containers:
        - name: sqitch
          image: psankar/vetchi-sqitch:latest
          command: ["sh", "-c"]
          args:
            - |
              sqitch deploy --verbose db:pg://user:password@postgres:5432/vetchidb
              sqitch verify --verbose db:pg://user:password@postgres:5432/vetchidb
      restartPolicy: Never
