apiVersion: batch/v1
kind: Job
metadata:
  name: sqitch
  namespace: vetchidev
spec:
  template:
    spec:
      backoffLimit: 5
      containers:
        - name: sqitch
          image: psankar/vetchi-sqitch:latest
          command: ["sh", "-c"]
          args:
            - |
              sqitch deploy --verbose db:pg://user:pass@postgres:5432/vdb
              sqitch verify --verbose db:pg://user:pass@postgres:5432/vdb
      restartPolicy: Never
