#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable --now docker

  # Add user to docker group (optional, for non-root usage)
  - usermod -aG docker ubuntu

  # Install kubectl
  - curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update
  - apt-get install -y kubectl

  # Install Helm 
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  
  # Add Helm repo for CloudNativePG
  - helm repo add cnpg https://cloudnative-pg.github.io/charts
  - helm repo update

  # Install k3d (Lightweight Kubernetes)
  - curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

  # Create a test Kubernetes cluster with k3d
  - k3d cluster create my-cluster

  # Verify installation (store output in a log file)
  - docker --version > /root/install-log.txt
  - kubectl version --client >> /root/install-log.txt
  - helm version >> /root/install-log.txt
  - k3d --version >> /root/install-log.txt
