#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - software-properties-common

runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable --now docker

  # Add user to docker group (optional, for non-root usage)
  - usermod -aG docker ubuntu

  # Install kubectl (updated method)
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/

  # Install Helm
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  # Install k3d (Lightweight Kubernetes)
  - curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

  # Create a Kubernetes cluster with k3d with proper port mappings
  - k3d cluster delete my-cluster || true
  - k3d cluster create my-cluster --api-port 6550 --port "80:80@loadbalancer" --port "443:443@loadbalancer" --agents 2
  - sleep 10 # Wait for cluster to be ready
  - k3d kubeconfig merge my-cluster --kubeconfig-switch-context

  # Verify installation (store output in a log file)
  - docker --version > /root/install-log.txt
  - kubectl version --client >> /root/install-log.txt
  - helm version >> /root/install-log.txt
  - k3d --version >> /root/install-log.txt
  - kubectl get nodes >> /root/install-log.txt
