apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
    spec:
      containers:
        - name: harrypotter
          image: harrypotter:latest
          ports:
            - containerPort: 3000
