# CloudNativePG cluster configuration
postgresCluster:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: postgres

# Minio configuration
minio:
  rootUser: minioadmin
  rootPassword: minioadmin
  persistence:
    size: 10Gi
  service:
    ports:
      api: 9000
      console: 9001

# Mailpit configuration
mailpit:
  replicaCount: 1
  service:
    smtp:
      port: 1025
    http:
      port: 8025
