apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  namespace: vetchidev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
    spec:
      containers:
        - name: ronweasly
          image: psankar/ronweasly:latest
          ports:
            - containerPort: 3000
