apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vetchidev-full-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqitch-sa
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sqitch-full-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vetchidev-full-access
subjects:
  - kind: ServiceAccount
    name: sqitch-sa
    namespace: {{.Release.Namespace}}
