apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
  namespace: vetchidev
data:
  config.json: |
    {
      "env": "dev",
      "onboard_token_life": "3m",
      "port": "8080"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
  namespace: vetchidev
spec:
  serviceName: "granger"
  replicas: 1
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
    spec:
      containers:
        - name: granger
          image: psankar/granger:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
          volumeMounts:
            - name: config-volume
              mountPath: /etc/granger-config
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
  namespace: vetchidev
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
