apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
  namespace: vetchidev
data:
  config.json: |
    {
      "env": "dev",
      "onboard_token_life": "3m",
      "port": "8080",
      "postgres": {
        "db": "vdb",
        "host": "postgres",
        "port": "5432",
        "user": "user"
      },
      "smtp": {
        "host": "smtp",
        "port": "587",
        "user": "user"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
  namespace: vetchidev
spec:
  serviceName: "granger"
  replicas: 1
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
    spec:
      containers:
        - name: granger
          image: psankar/granger:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: granger-config
                  key: port
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: SMTP_PASSWORD
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
  namespace: vetchidev
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
