apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
  namespace: vetchidev
data:
  port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
  namespace: vetchidev
spec:
  serviceName: "granger"
  replicas: 1
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
    spec:
      containers:
        - name: granger
          image: psankar/granger:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: granger-config
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              value: "postgres"
            - name: SMTP_HOST
              value: "mailpit"
            - name: SMTP_PORT
              value: "1025"
            - name: SMTP_USER
              value: "user"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: SMTP_PASSWORD
            - name: ENV
              value: "dev"
            - name: ONBOARD_TOKEN_VALID_MINS
              value: "4m"
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
  namespace: vetchidev
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
