apiVersion: v1
kind: ConfigMap
metadata:
  name: hermione-config
  namespace: vetchidev
data:
  port: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermione
  namespace: vetchidev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hermione
  template:
    metadata:
      labels:
        app: hermione
    spec:
      containers:
        - name: hermione
          image: psankar/hermione:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: hermione-config
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PORT
            - name: SESSION_TOKEN_VALID_MINS
              value: "3m"
            - name: LONG_TERM_SESSION_VALID_MINS
              value: "5m"
      volumes:
        - name: config-volume
          configMap:
            name: hermione-config
---
apiVersion: v1
kind: Service
metadata:
  name: hermione
  namespace: vetchidev
spec:
  selector:
    app: hermione
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
