apiVersion: v1
kind: ConfigMap
metadata:
  name: hermione-config
  namespace: vetchidev
data:
  config.json: |
    {
      "employer": {
        "tfa_tok_life": "5m",

        "session_tok_life": "15m",
        "lts_tok_life": "730h",

        "employee_invite_tok_life": "5m"
      },
      "hub": {
        "web_url": "https://vetchi.org",
        "tfa_tok_life": "5m",

        "session_tok_life": "15m",
        "lts_tok_life": "730h",

        "hub_user_invite_tok_life": "5m",
        "password_reset_tok_life": "5m"
      },
      "port": "8080",
      "postgres": {
        "db": "vdb",
        "host": "postgres",
        "port": "5432",
        "user": "user"
      },
      "timing_attack_delay": "1s"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermione
  namespace: vetchidev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hermione
  template:
    metadata:
      labels:
        app: hermione
    spec:
      serviceAccountName: hermione-sa
      initContainers:
        - name: wait-for-sqitch
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get job sqitch -n vetchidev -o jsonpath='{.status.succeeded}' | grep -q '1'; do
                echo "Waiting for sqitch job to complete..."
                sleep 5
              done
      containers:
        - name: hermione
          image: psankar/hermione:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hermione-config
      volumes:
        - name: config-volume
          configMap:
            name: hermione-config
---
apiVersion: v1
kind: Service
metadata:
  name: hermione
  namespace: vetchidev
spec:
  selector:
    app: hermione
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hermione-sa
  namespace: vetchidev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hermione-full-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: hermione-sa
    namespace: vetchidev
