apiVersion: v1
kind: ConfigMap
metadata:
  name: hermione-config
  namespace: vetchidev
data:
  config.json: |
    {
      "employer": {
        "lt_session_tok_life": "5m",
        "session_tok_life": "3m",
        "tgt_life": "3m"
      },
      "port": "8080",
      "postgres": {
        "db": "vdb",
        "host": "postgres",
        "port": "5432",
        "user": "user"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermione
  namespace: vetchidev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hermione
  template:
    metadata:
      labels:
        app: hermione
    spec:
      containers:
        - name: hermione
          image: psankar/hermione:latest
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vetchi-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hermione-config
      volumes:
        - name: config-volume
          configMap:
            name: hermione-config
---
apiVersion: v1
kind: Service
metadata:
  name: hermione
  namespace: vetchidev
spec:
  selector:
    app: hermione
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
